#!/usr/bin/perl -CSDAL

use warnings;
use strict;
use IServ::Host::Detect;
use IServ::SSH;
use POSIX qw(strftime);

/^[\d.]+$/ or die "ip invalid\n" for @ARGV;

my $m_unix = qr/^Unix-like/;
my @ips_online;
my @tests = ("sshd");

# determine online IPs; dead IPs have long timeouts
my $result = IServ::Host::Detect::Analyze(\@ARGV, \@tests, scalar @ARGV);

for (sort keys %$result)
{
  push @ips_online, $_ if defined $result->{$_}{os} and
      $result->{$_}{os} =~ $m_unix;
}

for my $ip (@ips_online)
{
  # Calculate shutdown time, because the shutdown implementations of the linux distributions are may different
  my $unix_time = time;
  my $shutdown_time = $unix_time + 10 * 60;   # ten minutes after current time
  my @local_shutdown_time = localtime $shutdown_time;
  my $time_string = strftime "%H:%M", @local_shutdown_time;

  () = IServ::SSH::ssh_run $ip, "shutdown -P $time_string";
}

