#!/usr/bin/perl -T -CSDAL

use warnings;
use strict;
use utf8;

undef %ENV;

(print STDERR "Usage: samba_print_directory [act]\n" and exit 1) if @ARGV < 1;

my $m_uid = qr/^(\d+)$/;
my ($act) = @ARGV;
my (undef, undef, $uid, $gid, undef, undef, undef, $home) = getpwnam $act or die "getpwnam for $act failed: $!";
my $dir = "$home/Print";

# untaint variables
if ($dir =~ /^(.*)$/)
{
  $dir = $1;
}

if ($uid =~ $m_uid)
{
  $uid = $1;
}

if ($gid =~ $m_uid)
{
  $gid = $1;
}

die "UID too low!" if $uid < 500;

-d $dir or mkdir $dir or die "Couldn't make directory $dir: $!";
chown $uid, $gid, $dir or die "Couldn't chown directory $dir: $!";
chmod 02770, $dir or die "Couldn't chmod directory $dir: $!";
